### ISSUE TITLE
Admin guide for making additional admin workstations

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop-docs#256]
## Describe the change
Add a dedicated step-by-step admin guide to creating a second/additional admin workstation.

## How will this impact users?
This will give SD admins an easy guide to make additional admin drives for other additional admins, without needing to hunt for instructions across multiple parts of the docs.

## Additional context
Currently, we have some instructions on how to build an admin workstation from scratch as part of the SD installation, rebuilding an admin workstation if it's been lost, and a guide to provisioning additional journo workstations. This guide would ideally be similar in scope to some parts of the [Onboard Journalists page](https://docs.securedrop.org/en/stable/onboarding.html#onboard-journalists) but with instructions for ssh-related ATHS files to include, and generating/uploading new SSH pubkeys.

**Comment by eloquence** [comment]
I'm starting on this before the docsprint because procedures for provisioning, managing & restoring Admin Workstation USBs are easily one of our most frequent support issues.

Here's the outline of the procedure I would recommend, which I've just verified.

Existing Admin Workstation: AW1
Newly provisioned Admin Workstation: AW2

1. Recap caveats when [multiple admins make configuration changes](https://docs.securedrop.org/en/stable/admin.html#managing-configuration-updates-with-multiple-admins) 
2. Create a fresh Tails drive (can be done [using Tails installer](https://tails.boum.org/install/clone/index.en.html#install-tails) from AW1). This will be AW2.
3. Boot AW2 drive and configure persistent volume 
4. Copy `~/Persistent/securedrop` directory from AW1 to AW2 using `rsync -a`. Do NOT copy `~/.ssh` to AW2
5. Generate new keypair using `ssh-keygen -t rsa -b 4096` on AW2 (this ensures the privkey is never written to disk on AW1 so cannot accidentally remain there)
7. Boot AW1 and mount AW2. Run `ssh-copy-id <username>@app -i <path to id_rsa.pub on AW2>`; repeat for mon
8. Boot into AW2 and run `./securedrop-admin tailsconfig` in `~/Persistent/securedrop`. 
9. Confirm SSH access
10. Create new account in Journalist Interface for new admin and have them store creds in their password manager on AW2

**Comment by eloquence** [comment]
A fleshed out version of this workflow (still WIP) is in 8baeef5504b3f5382c08242c62fa815a12a7d791. If there are no concerns with this approach conceptually, I'll get it into shape in coming days.

**Comment by huertanix** [comment]
Just checked out the branch and took a look-see. The raw steps seem to be all there afaik. Is the plan to have the 24-step bulleted list be expounded on and look like the format used by other guides in the docs?

**Comment by eloquence** [comment]
Thanks much for taking a spin! I've deliberately kept it short to follow more of a how-to approach as per Divio's [documentation system](https://documentation.divio.com/). If there are areas that would benefit from additional explanation, I think my preference in this chapter would be to link out to to them, rather than make the steps longer / more difficult to follow. What do you think?

**Comment by huertanix** [comment]
Yeah, I figure some steps could be bolstered with some minor additional extrapolation. Although admins can be presumed to be tech-savvy, many coming from a Windows background may be pretty new to Linux, so concepts like mounting an encrypted volume for a Tails drive plugged into the workstation rather than the one that's currently running is going to be new to them.

So things like what's currently step 10 may be helped with some verbal handrails to explain what's happening, for example, since "Insert AW1 and unlock it using the file manager" is something that may not immediately bring to mind the admin's only other experience with unlocking LUKS volumes with Nautilus. Something like "...just as you would with a Transfer Device, but using the Persistent Volume passphrase for AW1 to unlock it" or something along those lines may help though.
