### ISSUE TITLE
Add NUC11 docs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-docs#307]
SD 2.2.0 will add NUC11 support (https://github.com/freedomofpress/securedrop/issues/6170). We should document this similar to  https://docs.securedrop.org/en/stable/hardware.html#intel-10th-gen-nuc , which means we also have to:
- confirm that wireless removal docs are still accurate (requires opening up the device)
- confirm that BIOS instructions are still accurate

**Comment by zenmonkeykstop** [comment]
At the very least BIOS screens will need updating. The wireless leads are still detachable (took photos when preparing mine) so that part won't change much. 

One change that I did make in terms of BIOS config was to disable SGX - we don't use any related functionality AFAIK, and dsabling it clears a speculative execution check.

**Comment by eaon** [comment]
Can confirm, the NUC11 and NUC10 insides are more or less identical, but I also took pictures.

Regarding SGX, I double checked just to make sure, the [i3-1115g4 CPU in my NUC11PAHi3](https://www.intel.com/content/www/us/en/products/sku/208652/intel-core-i31115g4-processor-6m-cache-up-to-4-10-ghz/specifications.html) does not support it, so it doesn't show up at all. Depending on which NUC11 models we recommend, the language around BIOS configuration may benefit from clarification there, at least I was temporarily worried that maybe BIOS update had removed the ability to disable SGX or something like that.
