### ISSUE TITLE
Research alternatives to NUC server hardware

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#480]
Intel has recently announced they will be discontinuing their line of NUC hardware. As we recommend them for SD servers, we will need to refresh said recommendation.

**Comment by nathandyer** [comment]
After a timeboxed investigation, I have determined that these are the most realistic options that we have for recommended server models following Intel's decision to discontinue the NUC line:

System | Links | Price
-- | -- | --
Bee-link SER5 PRO 5700U | https://www.bee-link.com/computer-73493777 | $169.00
Framework Mainboard + Cooler Master Mainboard Case | https://frame.work/marketplace/mainboards https://frame.work/products/cooler-master-mainboard-case | $39+$199+
LattePanda Sigma | https://www.lattepanda.com/lattepanda-sigma | $579.00
LattePanda 3 Delta | https://www.lattepanda.com/lattepanda-3-delta | $279.00
Purism Librem Mini | https://puri.sm/products/librem-mini/ | $799.00
ACEMAGICIAN Ryzen7 PC | https://www.amazon.com/Computers-Windows-Display-Desktop-Bluetooth/dp/B0BQHBWPYX | $279.00
ASUS Nuc 14 Pro | https://www.asus.com/displays-desktops/nucs/nuc-mini-pcs/asus-nuc-14-pro/ | TBD; Not yet available

While other small form factor PCs exist, the others I found appeared to be mostly knock-offs or from obscure/untrustworthy manufacturers.

## Notable Omissions

I have specifically decided not to include the System76 Meerkat, as it is currently based on the Intel NUC line that has been discontinued.

## Personal Opinions

Of these options, there are three of particular interest to me. The obvious candidate would be the NUC 14 Pro, which is the next of the official NUC line now that Asus has taken it over. That being said, it has only been announced within the past week (at CES), does not currently have a known price or ship date, and has some "AI-focused" features that make me skeptical.

The best overall deal appears to be the ACEMAGICIAN Ryzen7 PC, which comes fully assembled with RAM and SSDs, for $279.00. Paired with a Ryzen7 CPU, it seems to be an incredible bang for the buck.

From a pure configurability standpoint, I also find the Framework Mainboard + Cooler Master Mainboard Case option quite compelling. It can be powered off a USB-C connection, and it's easy to swap in ports/components. There's even a case to be made that you could use a Framework for the SVS/Admin Workstation, then "retire" its mainboard for life as a server when it comes time for upgrades.

On the whole though, I still find the ACEMAGICIAN Ryzen7 the most compelling, pending real-world usage tests.

**Comment by zenmonkeykstop** [comment]
Looks like Asus has a 13th-gen line already available. Any reason not to include those in the analysis? I'd be biased towards established vendors because a) probably gonna be easier for folks working with corporate procurement and b) probably going to have better long-term support for stuff like BIOS updates. Looking at the AceMagician option for example, it's a rebadged generic mini-pc that seems to have been discontinued already and that no longer has any level of support (see https://acemagic.de/en/pages/drivers-downloads).

As an aside, it's great that Framework has options for reuse of mainboards and such but I'd be very leery of using them for servers with 24/7 uptime expectations. Also, IMO the ability to swap ports and components quickly is actually a negative in our use case. It would probably be pretty trivial to rubberduckify a Framework USB widget.

The biggest reasons that NUCs have been the default recco for so long are broad availability (often at retail), consistent support, and minimal need for customization or hardware modifications. It would be worth considering new options with these factors in mind.

**Comment by nathandyer** [comment]
@zenmonkeykstop Those are all excellent points! For the question about including the 13th Gen NUCs, as I understand it those are the last generation that were made directly by Intel, and I erroneously was thinking we _already_ had tested them and listed them on our recommended hardware page. Regardless of the decision we make about post-Intel recommendations, I think it makes sense for us to work the 13th Gen NUCs into our fleet of test systems for QA work.

**Comment by nathandyer** [comment]
Following up to my previous note, the NUC 13 is definitely something we should support. This is the last NUC version that is officially produced by Intel itself. There are a few different models available (including an extreme line intended for gaming), but I think we should continue recommending the Pro line. The NUC13ANHi5 looks to me like the unit we would want to target (available on backorder from [SimplyNUC](https://simplynuc.com/product/nuc13anhi5-full/), with basic [support docs here](https://www.intel.com/content/dam/support/us/en/documents/intel-nuc/NUC13ANH_L10_UserGuide.pdf)).

The support guide doesn't mention if the wireless adapter is removable. In looking at photos, my best guess is that the antennas can be removed, but I can't tell if the wireless card is removable or built into the motherboard (it looks to be underneath the M.2 SSD slot).

I would be in favor of purchasing a unit once it becomes available in February, and incorporating it into our standard QA fleet.

Looking beyond the NUC13, I do think having a rough plan for future support is a good idea. My inclination/recommendation would be for us to plan on using the official ASUS NUC line, which will pick up right where Intel left off. [The NUC14](https://www.asus.com/displays-desktops/nucs/nuc-mini-pcs/asus-nuc-14-pro/) looks to be a continuation of the line rather than a complete overhaul, so unless there are any changes under the hood, that seems like the obvious choice for us. 

Based on @zenmonkeykstop's earlier comment, I think we can safely take the ACEMAGICIAN out of the running, as well as the Framework (I do think it's an interesting option to explore down the road, but is a bit too experimental for now), and the Purism Librem Mini. If we do want to ever pursue the LattePanda or Bee-link options, I was able to confirm that they all have removable wireless network cards.

**Comment by nathandyer** [comment]
I recommend that we proceed with acquiring a NUC13ANHi5 (available here from [SimplyNuc](https://simplynuc.com/product/nuc13anhi5-full/)), which the following specs:

* No vPro
* 8GB RAM
* 256GB SSD
* No additional drives
* No OS
* 1 year basic support

(Note: these are all the default options, except for more RAM. 4GB of RAM would likely be sufficient if we prefer to save the $40, but I think we might get more mileage out of it as a test unit with the extra memory) (cc: @zenmonkeykstop)

**Comment by nathandyer** [comment]
We had already ruled them out, but just noting an important piece of news here: AceMagic mini-PCs were recently discovered to be shipping with spyware: https://www.tomshardware.com/desktops/mini-pcs/mini-pc-maker-ships-systems-with-factory-installed-spyware-acemagic-says-issue-was-contained-to-the-first-shipment
