### ISSUE TITLE
document Tor proof-of-work defense

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-docs#568]
## Describe the change

What documentation should we offer for the Tor proof-of-work defense implemented in freedomofpress/securedrop#7175?
- Just how to enable it
- How to monitor it (non-invasively) via `onionprobe`
- More? something else?

## Additional context

**Comment by cfm** [comment]
@zenmonkeykstop and @nathandyer, let me know what documentation you think will be most useful here, and I'll draft it.

**Comment by nathandyer** [comment]
My instinct here is that this is the sort of feature that requires minimal documentation, as it doesn't really have many user-facing implications. I don't expect that active monitoring will be something that admins will need to do, and I think even mentioning `onionprobe` might be a bit far since it requires the extra package install in Tails (and is broken in bookworm/Tails6.x).

I think documenting this as part of the `./securedrop-admin sdconfig` workflow is likely sufficient, noting that the option exists, and briefly explaining why an admin may or may not want to enable it (similar to how we handle the SSH-over-Tor option).

**Comment by cfm** [comment]
Thanks, @nathandyer.  This is ready for review in #569.
