### ISSUE TITLE
Documentation about OSSEC alert levels 

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop-docs#69]
# Feature request

## Description

We need better documentation on what each OSSEC alert means for administrators. For example, what makes an alert level 7 instead of 3. If a file hash changes, what does that mean for me. 

## User Stories

As a Securedrop admin, I need to know _exactly_ what each alerts means that is emailed to me.

**Comment by eloquence** [comment]
@joaedwar Good candidate issue for you to work on, will require extracting the changes in the above commit and applying them to current `main` in a PR, we can then help with review for needed updates/accuracy.

**Comment by creviera** [comment]
Regarding documentation about ossec alerts, it would also be useful to have a way to connect each ossec alert (via an alert id or email header for example) to the relevant section in the docs. Right now, it seems like there is a disconnect between alerts/logs and the docs, in part, because we intentionally avoid adding links (whether or not this is something we want to continue is up for debate).

**Comment by creviera** [comment]
For example, we have the following alert: https://github.com/freedomofpress/securedrop/blob/8c86e8ee717c4971a34e8555b41f6e9d82e4870e/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml#L210-L226

And the following docs: https://docs.securedrop.org/en/stable/admin.html#cleaning-up-deleted-submissions

But how do we connect the two so that we can lead an admin down a happy path :D?
